### ISSUE TITLE
GWorld.GetRandomReachablePointInRadius is not a function

### ISSUE THREAD

**Issue by dalou** [ncsoft/Unreal.js-demo#13]
Unreal Engine: Version: 4.25.1-13594126+++UE4+Release-4.25
Unreal.js Plugin : installed from marketplace (the manual compilation doesn't work at all)
Node : v15.4.0

After one little correction for nodejs latest 
let cmd = -e console.log([...process.argv[0].replace(/\\\\/g,'/').split('/').slice(0,-1),'node_modules/**npm/bin/npm-cli.js**'].join('/'))

I have got an error on GetRandomReachablePointInRadius  from GWorld

Warning: Undefined required script './reactProdInvariant'
Error: TypeError: GWorld.GetRandomReachablePointInRadius is not a function
    at wander (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/dummy-ai.js:29:26)
    at random (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/dummy-ai.js:35:15)
    at loop (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/dummy-ai.js:99:19)
    at async behaviortree (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/dummy-ai.js:111:9)
    at async mixamo (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/dummy-ai.js:152:5)
    at async Promise.all (index 1)
    at async demo (file:///d:/EU4Projects/JavascriptTest/Content/Scripts/demos/demo-ai.js:15:5)

**Comment by dalou** [comment]
Notice that others Cables, Rest, Deep learning and React works fine
